name: Activation

on:
  workflow_dispatch:

jobs:
  activate:
    name: Activate Unity License
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        with:
          unityVersion: 2022.3.7f1 # optional, default is 2019.2.11f1
